### ISSUE TITLE
Geist font renders OK on iPhone and Mac, but not on Windows (multiple browsers)

### ISSUE THREAD

**Issue by jakekugel** [trevortylerlee/astro-micro#33]
Thanks for this blog template, it looks great and I'm using it to build a website.

The Geist font appears correctly when using Mac and iPhone, but doesn't appear to render correctly on Windows--instead I see the system-ui font used.  I've tried Chrome, Firefox, and Edge.

Here is the live demo site for Astro Micro, and what the Chrome "WhatFont" extension shows when I click on the title.

![image](https://github.com/trevortylerlee/astro-micro/assets/5317558/fb73c956-3eb3-44a7-9dcb-a37b6884993b)

I do see the fonts being loaded in the Chrome network tab:

![image](https://github.com/trevortylerlee/astro-micro/assets/5317558/c83a6a6f-b3a9-4674-83a4-70bdb281569d)

**Comment by trevortylerlee** [comment]
Hi Jake, thanks for opening this issue.

I ended up installing the fonts via fontsource to get it working on Windows (screenshot below—an easy tell are the l's in Geist, which have a small scoop at the end). Let me know if this works for you and I'll close the issue.

While researching I did come across [this issue on Astro](https://github.com/withastro/astro/issues/10425). Astro Micro was also getting these warnings, but they aren't related to the fonts not rendering on Windows. That issue is fixed now anyways as I removed the preloading fonts in this commit as well.

Funnily enough that issue was created by Mark Horn, creator of Astro Nano which is what Astro Micro is forked off of! I did notice Astro Nano's fonts seem to work fine on Windows...

![geist-on-windows](https://github.com/trevortylerlee/astro-micro/assets/49603972/86057e85-4988-4dc5-b54f-fff7b8d7ac31)

**Comment by jakekugel** [comment]
I ran your branch locally and it fixed the issue, thanks much!!  Also, I'm impressed that you fixed it so fast.

I'll continue to build my site and I'll send you a link when it is finished so you can see how others are using your template.

Cheers,
Jake
